on:
  push:

jobs:
  publish:
    strategy:      
      matrix:
        number: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        include:
          - name: "@jcansdale-test/npm-errors"
          - repository: "https://github.com/${{ github.repository }}"
          - _authToken: "${GITHUB_TOKEN}"
          - registry: https://npm.pkg.github.com
          - number: 0
          - number: 1
            name: "@jcansdale-test/NPM-ERRORS"
          - number: 2
            name: "@JCANSDALE-TEST/npm-errors"
          - number: 3
            name: "@jcansdale-missing/npm-errors"
          - number: 4
            repository: "https://github.com/jcansdale/nuget-errors"
          - number: 5
            _authToken: "invalid"
          - number: 6
            _authToken: ""
          - number: 7
            registry: https://npm.pkg.github.com/jcansdale-test
          - number: 8
            registry: https://npm.pkg.github.com/@jcansdale-test
          - number: 9
            registry: https://npm.pkg.github.com/jcansdale
          - number: 10
            registry: https://npm.pkg.github.com/---unknown---
          - number: 11
            registry: https://registry.npmjs.org
          - number: 12
            registry: https://github.org
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: create package.json
      run: |
        cat <<- EOF > package.json
        {
          "name": "${{ matrix.name }}",
          "version": "1.0.0-g${{ github.sha }}-${{ matrix.number }}",
          "repository": "${{ matrix.repository }}"
        }
        EOF
    - run: echo '//npm.pkg.github.com/:_authToken=${{ matrix._authToken }}' > .npmrc
    - run: npm publish --registry=${{ matrix.registry }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
