on:
  push:

jobs:
  publish:
    strategy:      
      matrix:
        name:
          - "@${{ github.repository }}"

    runs-on: ubuntu-latest

    steps:
    - name: create package.json
      run: |
        cat <<- EOF > package.json
        {
          "name": "${{ matrix.name }}",
          "version": "1.0.0-g${{ github.sha }}",
          "repository": "https://github.com/${{ github.repository }}"
        }
        EOF
    - run: echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' > .npmrc
    - run: npm publish --registry=https://npm.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
