on:
  push:

jobs:
  publish:
    strategy:      
      matrix:
        number: [0, 1, 2, 3]
        include:
          - number: 0
            name: "@${{ github.repository }}"
          - number: 1
            name: "@jcansdale-test/NPM-ERRORS"
          - number: 2
            name: "@JCANSDALE-TEST/npm-errors"
          - number: 3
            name: "@jcansdale-missing/npm-errors"
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: create package.json
      run: |
        cat <<- EOF > package.json
        {
          "name": "${{ matrix.name }}",
          "version": "1.0.0-g${{ github.sha }}-${{ matrix.number }}",
          "repository": "https://github.com/${{ github.repository }}"
        }
        EOF
    - run: echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' > .npmrc
    - run: npm publish --registry=https://npm.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
